### ISSUE TITLE
Title is empty in Explorer

### ISSUE THREAD

**Issue by J-Siu** [masonicboom/vscode-web-browser#3]
Title is empty in Explorer.
![screen shot 2016-08-13 at 18 29 44](https://cloud.githubusercontent.com/assets/3171920/17645978/005b8c18-6184-11e6-9bb8-aa623e3bf023.png)

**Comment by ScorpioCoding** [comment]
Personally don't use the open editors.

**Comment by ScorpioCoding** [comment]
@J-Siu  I do not have a mac, can you test this fix on your mac, please? thnx.

**Comment by J-Siu** [comment]
This issue no longer exist and can be close. Thank you!
